# Load Modules
LoadModule mpm_event_module modules/mod_mpm_event.so
LoadModule authn_core_module modules/mod_authn_core.so
LoadModule authz_core_module modules/mod_authz_core.so
LoadModule unixd_module modules/mod_unixd.so
LoadModule proxy_module modules/mod_proxy.so
LoadModule proxy_http_module modules/mod_proxy_http.so
LoadModule cache_module modules/mod_cache.so
LoadModule cache_disk_module modules/mod_cache_disk.so
LoadModule rewrite_module modules/mod_rewrite.so

# Basic server config
ServerName localhost
Listen 80
ErrorLog /proc/self/fd/2
LogLevel warn

<VirtualHost *:80>
    ServerName localhost

    # Security filtering
    RewriteEngine On

    RewriteRule ^/system/console(.*)$ - [F,L]
    RewriteRule ^/bin/(.*)$           - [F,L]
    RewriteRule ^/etc/(.*)$           - [F,L]

    # Proxy exclusions - second layer of defence
    ProxyPass /system/console !
    ProxyPass /bin/           !
    ProxyPass /etc/           !

    # Disk Cache
    CacheEnable disk /
    CacheRoot /var/cache/apache2/proxy
    CacheDefaultExpire 300
    CacheMaxExpire 300
    CacheIgnoreNoLastMod On

    # Reverse Proxy to Sling
    ProxyPass        / http://host.docker.internal:8080/
    ProxyPassReverse / http://host.docker.internal:8080/

</VirtualHost>